### ISSUE TITLE
Cant get it to work in Opera or Firefox

### ISSUE THREAD

**Issue by mkoczorowski** [sdkcarlos/artyom.js#11]
Hi there,

Is this only restricted to chrome ? In firefox there is an error when initialising, in Opera it initialises fine, but info about using a microphone never pops up to give access, hence no voice commands work there.

Other than that awesome job!

**Comment by sdkcarlos** [comment]
Artyom.js only works in Google Chrome, in Opera the **speech synthesis** will "work" only with the native voice of the System.
