### ISSUE TITLE
Incorrect "main" parameter in package.json

### ISSUE THREAD

**Issue by murray484** [sdkcarlos/artyom.js#14]
When installing this library using npm, it fails to compile with the error "module not found".  It would seem that this is caused by the fact that the "main" parameter in package.json is set to "artyom.js" rather than "build/artyom.js".  I've tested this change on my computer and it solves the issue for me.

**Comment by murray484** [comment]
Upon further research, it seems that the real issue is that the NPM package is not up to date.

**Comment by sdkcarlos** [comment]
@murray484 I've just published artyom v1.0.4 with the correct main parameter (ts/artyom.js). However after the installation of the latest version the error "module not found" persists ...

 @semagarcia  any idea of what's happening ?

**Comment by sdkcarlos** [comment]
The configuration work as expected, it was just a problem in the project that i tested. The artyom package in NPM is up to date.
