### ISSUE TITLE
I can call a function when artyom don't identify a command?

### ISSUE THREAD

**Issue by LuisAraujo** [sdkcarlos/artyom.js#17]
Hello,

I wanna know if is possible (and how) call a function when artyom not identify any command, eg. if not identify say "Sorry, I don't did understand your command". 

Thanks.

**Comment by sdkcarlos** [comment]
Hey @LuisAraujo that's not possible till the date.

However that's a good idea and i could think about trying to achieve it for the next version, it wouldn't be so reliable with the current codebase ... but the result should be acceptable.

**Comment by sdkcarlos** [comment]
Now since artyom 1.0.4 you can use the `NOT_COMMAND_MATCHED` event to know when the user speech doesn't matches with any of the loaded commands e.g :

```javascript
// Add a single command
artyom.on(['Good morning']).then((i) => {
    console.log("Good morning, you're looking good today");
});

// Add the event listener
artyom.when("NOT_COMMAND_MATCHED", () => {
    artyom.say("I'm sorry, i didn't understand what you mean. Maybe you should buy a new microphone ... or add more commands, yeah that would be better.");
});

// initialize artyom
artyom.initialize({
    lang: "en-GB",
    continuous: true,
    debug:true,
    listen: true
});

// Be sure that you don't add more commands and say "i'm hungry"
// Then you should listen artyom because the "i'm hungry" command doesn't exists
```
