### ISSUE TITLE
duplicate responses on android chrome

### ISSUE THREAD

**Issue by yummycarp** [sdkcarlos/artyom.js#18]
I have the same problem this guy had. Here is a solution but artyom does not expose all these variables.

recognition.continuous = false;
recognition.interimResults = false;
recognition.maxAlternatives = 1;

http://stackoverflow.com/questions/35112561/speech-recognition-api-duplicated-phrases-on-android

**Comment by sdkcarlos** [comment]
Fixed in artyom v1.0.5.
