### ISSUE TITLE
Custom Dictionary Words & Phonetics

### ISSUE THREAD

**Issue by skibulk** [sdkcarlos/artyom.js#2]
Are custom words supported? Can I use Phonetic spelling to enhance speech & speech recognition while using custom words?

**Comment by sdkcarlos** [comment]
As artyom uses speechRecognition API , there's no way to customize the grammar because it is retrieven from the Google Servers. The spelling (a,b,c ) works but for short words. You can open the Console in an artyom demo and see how your spelling is recognized.

Can you provide an example of what do you want to achieve ?

**Comment by skibulk** [comment]
I wanted to use exotic names, for example: http://www.huffingtonpost.com/2014/10/01/rare-and-unusual-baby-names_n_5888536.html

**Comment by skibulk** [comment]
I also wanted to improve the the accuracy of difficult words: https://www.vocabulary.com/lists/191545#view=notes

Using Phonetics, For example,
abrogate
ab·ro·gate
ˈabrəˌɡāt/

**Comment by sdkcarlos** [comment]
@skibulk unfortunately artyom is just a wrapper of the webkitSpeechRecognition api and doesn't support such customization. However the google service is very good and recognizes almost everything correctly (obviously something with sense).

![Abrogate example](https://cloud.githubusercontent.com/assets/11634719/15117974/64f76248-160a-11e6-9909-6563f8406740.png)

```javascript
artyom.addCommands({
   indexes:["abrogate"],
   action: function(i){
      // i = 0
      // do something if abrogate
   }
});
```

Finally, this project JuliusJS seems to help with what you want , [see the homepage here](https://github.com/zzmp/juliusjs).
