### ISSUE TITLE
I've couldn't use the Library 

### ISSUE THREAD

**Issue by hunter-x** [sdkcarlos/artyom.js#21]
Hello,
I've just installed the library, but I'm getting :  artyom.say is not a function
```
var artyom= require ('artyom.js');
 artyom.say('hi');
```
Am I doing something wrong ?

**Comment by sdkcarlos** [comment]
If you're using artyom as a module from NPM, you need to declare a new instance of artyom as shown in the [Usage of artyom with Angular](https://github.com/sdkcarlos/artyom.js#with-angular2-typescript):

```javascript
var ArtyomBuilderInstance = require("artyom.js").ArtyomBuilder;

var artyom = ArtyomBuilderInstance.getInstance();

artyom.say("Hello World !");
```

**Comment by hunter-x** [comment]
Thank you for the help, it worked in react.
Is there a way to use it in the backend with node js ?
