### ISSUE TITLE
Speech recognition stops after executing command

### ISSUE THREAD

**Issue by ihabZhaika** [sdkcarlos/artyom.js#22]
Hi,
i am playing with the library , but had problem that when the speech matches a command it execute that command and stops , in the console it writes
```

Artyom.js:  << Executing Matching Recognition in normal mode >>
sentence accepted
VM774:12  Artyom.js   1 text chunk processed succesfully out of 1
```

my settings
"artyom.js": "^1.0.5",
i am using it with angular2  component

```
    if (artyom)
    {

      artyom.initialize({
                          lang:"en-GB",
                          debug:true, // Show what recognizes in the Console
                          listen:false, // Start listening after this
                          speed:0.9, // Talk a little bit slow
                          mode:"normal", // This parameter is not required as it will be normal by default
                          listen: true // Start to listen commands !
                        });
 artyom.addCommands([
                         {
                           indexes : ["execute *","listen *","robot *"] ,
                           smart:true,
                           action : (i,wildcard)=>
                           {
                             console.log("sentence accepted");
                             this.sentenceText =wildcard;
                             artyom.say("You said : "+wildcard);
                           }
                         } 
                       ]);
    }
```

so what could be the reason for it ? and how to fix it so it take the next command ?

**Comment by sdkcarlos** [comment]
Did you try to set [the continuous property at the initialization to true](http://docs.ourcodeworld.com/projects/artyom-js/documentation/methods/initialize#start-continuous-mode)? 

```javascript
artyom.initialize({
    // Run "forever"
    continuous: true,
    lang:"en-GB",
    debug:true,
    listen:false,
    speed:0.9, 
    mode:"normal",
    listen: true
});
```

By default artyom runs in no-continuous mode (a single command and stops). You need besides a https connection, otherwise you'll be prompted for permissions of the microphone everytime artyom restarts itself.

**Comment by ihabZhaika** [comment]
hi,
after applying what you suggested 
i get the following [ every second or so ] 
```
 Artyom.js:  Continuous mode enabled, restarting
 Artyom.js   Event reached : COMMAND_RECOGNITION_START
```

**Comment by sdkcarlos** [comment]
Yep, that's right artyom should now process multiple commands. You can set the debug property to false if you don't want log messages in the console.

**Comment by Abhi2109** [comment]
I am getting an error like Undefined Syntax error < on the first line of artyom.window.js

![image](https://user-images.githubusercontent.com/33317345/32711914-87628928-c867-11e7-93c0-3e5c4cd8ccf7.png)

**Comment by nischalbc** [comment]
@Abhi2109  Can you share the code from index page,  
 If you see the second error  "Artyom is not defined" , looks like the initialization didn't happen properly

**Comment by Abhi2109** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
   <script type="text/javascript" src="./artyom.window.js"></script>
   
  </head>
   <body>
   <div>
		<input type="button" onclick="startArtyom()" value="start voice command" /><br>
		<input type="button" onclick="stopArtyom()" value="end voice command" /><br>
   </div>
   <script>
   var artyom = new Artyom();
   
   artyom.addCommands([
   {
     //description:"Artyom can talk too, lets say something if we say hello world"
	 indexes:['hello'],
	 action:function(i){
	  // i = the index of the array of indices options
	  
	  if(i == 0 ){
	  artyom.say("Hello ! How are you?");
	  }
	 }
   },
   {
   indexes:['goodbye'],
   action:function(){
   alert("Now all is over..");
    }
   }
   ]);
   function startArtyom()
   {
   artyom.initialize({
   lang:"en-GB", //This is of type english for great britian we can add more
   continuous:true, //if you have https connection continuous can be activated..
   debug:true, //To show everything on chrome window..
   listen:true
   }).then(()=>{
        console.log("Artyom has been successfully initialie");
   }).catch((err)=>{
     console.error("Artyom could not be initialie:",err);
   });
   }
   
   function stopArtyom()
   {
     artyom.fatality();
   }
   
   
   
   
   
   </script>
   </body>
</html>
