### ISSUE TITLE
doesnt work on mobile browsers

### ISSUE THREAD

**Issue by benag** [sdkcarlos/artyom.js#23]

**Comment by benag** [comment]
the say command just didnt work on android chrome..

**Comment by sdkcarlos** [comment]
Perhaps is the Chrome Version of the device too old and it doesn't supports the speech synthesis ? You can check if the Speech Synthesis supported using [artyom.speechSupported](http://docs.ourcodeworld.com/projects/artyom-js/documentation/methods/speechsupported).
