### ISSUE TITLE
Doesnt work in Firefox

### ISSUE THREAD

**Issue by minalkArmstrong** [sdkcarlos/artyom.js#24]
I have one issue 
1.This plug in is not working in mozilla firefox  ,is there any way to resolve this issue.

**Comment by sdkcarlos** [comment]
Artyom.js only works in Google Chrome due to the exclusivity of the Speech Recognition API. Read more in the Docs [about requirements](http://docs.ourcodeworld.com/projects/artyom-js/documentation/getting-started/requirements#artyom-chrome).
