### ISSUE TITLE
Not sure where to place the output text dictation on the html body

### ISSUE THREAD

**Issue by popbijoux** [sdkcarlos/artyom.js#26]
Hi there, I have followed the instructions and looked into the demos but I still haven't been able to get it working. I know the microphone is working, the red dot fires, and I can't quite tell what I am doing wrong. i have used another voice recognition library so I am familiar with the basics.

I think what's missing is that on your tutorials you don't mention the text output code or area; I looked into the page sources and I found something but it doesn't work either...I am new to Javascript so there must be something I am missing:)
Btw I am NOT using artyom.js for voice commands, ONLY for dictation.

here's what I have [html]:
1. The two buttons that activate and deactivate

 ```
<input class="buttonRoundVoiceToTextWhite" type="button" onclick="startRecognition();" value="Recognize text" />
   <input class="buttonRoundVoiceToTextBlue hidden" type="button" onclick="stopRecognition();" value="stop recognition" />

```
2. the area (text input) where the text would go:
`<input id="artyom-redirect-output" type="text" name="lastname">`
//I also tried adding a span instead of the text input but that did not work either...
3. The full script with the artyom code, including some unrelated jquery code that works around these buttons to show and hide elements

```
<script>

$(".buttonRoundVoiceToAnimWhite").click(function() {
  $(".buttonRoundVoiceToAnimBlue").show();
    $(".buttonRoundVoiceToAnimWhite").hide();

});

$(".buttonRoundVoiceToAnimBlue").click(function() {
  $(".buttonRoundVoiceToAnimWhite").show();
    $(".buttonRoundVoiceToAnimBlue").hide();

});

$(".buttonRoundVoiceToTextWhite").click(function() {
  $(".buttonRoundVoiceToTextBlue").show();
    $(".buttonRoundVoiceToTextWhite").hide();

});

$(".buttonRoundVoiceToTextBlue").click(function() {
  $(".buttonRoundVoiceToTextWhite").show();
    $(".buttonRoundVoiceToTextBlue").hide();

});
//artyom 
var settings = {
    continuous:true, // Don't stop never because i have https connection
    onResult:function(text){
        // text = the recognized text
        console.log(text);
    },
    onStart:function(){
        console.log("Dictation started by the user");
    },
    onEnd:function(){
        alert("Dictation stopped by the user");
    }
};


var UserDictation = artyom.newDictation(settings);

function startRecognition(){
  UserDictation.start();
}

function stopRecognition(){
  UserDictation.stop();
}


artyom.redirectRecognizedTextOutput(function(recognized,isFinal){
    if(isFinal){
        console.log("Final recognized text: " + recognized);
    }else{
        console.log(recognized);
    }
});

//end of artyom



</script>
```
and I have this in the header: 

`<script src="artyom.min.js"></script>`

I would appreciate any pointers:) I am really interested in testing multiple languages, but first I want to make sure the basic stuff works:)
THANK YOU!

**Comment by sdkcarlos** [comment]
Hi, if you're not using voice commands you don't need the `redirectRecognizedTextOutput` function.

You can retrieve the recognized text from the dictation object in the `onResult` callback. Note that you have already set some event listeners to the buttons (start and stop) with jQuery, therefore isn't necessary to add new actions in the onclick attribute of the buttons.

The following code is the same as yours but simplified (and working):

```html
<!-- Buttons to start the dictation object -->
<input class="buttonRoundVoiceToTextWhite" type="button" value="Recognize text" />
<input class="buttonRoundVoiceToTextBlue hidden" type="button" value="stop recognition" />

<!-- In this input the recognized text will appear -->
<input id="artyom-redirect-output" type="text" name="lastname">

<script>
    // Configure artyom
    var UserDictation = artyom.newDictation({
        continuous: true, // Don't stop never because i have https connection
        onResult: function (text) {
            /** 
             * Set the recognized text as value of the text input
            **/
            $("#artyom-redirect-output").val(text);
        },
        onStart: function () {
            console.log("Dictation started by the user");
        },
        onEnd: function () {
            alert("Dictation stopped by the user");
        }
    });

    var btnAnimWhite = $(".buttonRoundVoiceToAnimWhite");
    var btnAnimBlue = $(".buttonRoundVoiceToAnimBlue");
    var btnVoiceTextWhite = $(".buttonRoundVoiceToTextWhite");
    var btnVoiceTextBlue = $(".buttonRoundVoiceToTextBlue");

    btnAnimWhite.click(function () {
        btnAnimBlue.show();
        btnAnimWhite.hide();
    });

    btnAnimBlue.click(function () {
        btnAnimWhite.show();
        btnAnimBlue.hide();
    });

    // Start recognition with the Recognize text button
    btnVoiceTextWhite.click(function () {
        // Start recognition
        UserDictation.start();

        btnVoiceTextBlue.show();
        btnVoiceTextWhite.hide();
    });

    // Stop recognition with the Stop recognition button
    btnVoiceTextBlue.click(function () {
        // Stop recognition
        UserDictation.stop();

        btnVoiceTextWhite.show();
        btnVoiceTextBlue.hide();
    });

</script>
```

The language of the dictation object will be the same [as the one providen with the initialization](http://docs.ourcodeworld.com/projects/artyom-js/documentation/methods/initialize).

As the problem isn't related to the library, this issue can be closed.

**Comment by popbijoux** [comment]
THANK YOU so much Carlos!!!! Just tested it it works perfectly YAAYYYY it's like magic:))))

**Comment by popbijoux** [comment]
Hi there carlos I was able to use this and it worked very well. I have a question related to switching languages in the browser, similar to how you used it in this application 
https://sdkcarlos.github.io/demo-sites/artyom/artyom_sticky_notes.html

Basically I am wondering if it's possible to have a command that will tell artyom to switch the language that it is recognizing.  For example I am bilingual in English and Portuguese. Is there a way to have a command that will switch the language after it has been initialized.

 If I say for example "Switch to Portuguese", and vice-versa, once the browser recognizes speech in Portuguese, I create a command that will tell it to go back to English. I see how you have the drop-down menu for several languages in the example above. It worked but it was not done via a speech command. 

I am not sure if 1. It can be done via command as opposed to clicking on browser button and 2. If not, how can I create a simple switch function that would allow me to move between 2 separate languages  (and display the text like I did using the example above I used in the past?

Thank you. I am not sure if I should post this as a separate question or continue here.

**Comment by sdkcarlos** [comment]
Hi @popbijoux , sorry for the late reply. Indeed, starting from scratch and doing it with the new version of Artyom could be tricky, therefore I wrote a detailed article with examples of how to switch from one language to other (multiple languages) using a single instance of Artyom or multiple. [You can find the article here](https://ourcodeworld.com/articles/read/643/how-to-switch-the-language-of-artyom-js-on-the-fly-with-a-voice-command).
