### ISSUE TITLE
[Feature Request] preferences for the voice

### ISSUE THREAD

**Issue by Derek-X-Wang** [sdkcarlos/artyom.js#29]
The current model will use the first match of voiceIdentifiersArray and speechSynthesis.getVoices().

It will be really handy if the users can have some control over the voice.

Something like user-defined preferences list. Check whether the voice in the list is available one by one, and failback to first match strategy if no match.

In initialization:
```
artyom.initialize({
    lang: "en-US", // US english
    speed: 1,
    debug: true, // Show messages in the console
    voice: ['Google US English', 'Alex'],
});
```

and able to change the voice when calling artyom.say()

I can do a PR if you don't have the time.

**Comment by Maximeesilv** [comment]
I have worked on this feature, after Forking the project ! Now I can the voice at init !
I agree with @Derek-X-Wang for a PR !

**Comment by Derek-X-Wang** [comment]
@Maximeesilv  Sounds good! would like to see your PR! So I don't have to do it myself :)

**Comment by sdkcarlos** [comment]
Hey, with the latest version 1.0.6 you could achieve this without a new property at the initialization.

By default, the voices identifiers (names) are stored within an array. When the voice is selected, the algorithm chooses the first one available (so if a voice with the given name doesn't exists, try with the next and so on), if none available it uses the default UK English.

So if you want a preference for your voice, you should just push the name of your favorite voice at the beginning of the identifiers array for the `en-US` voices:

```javascript
// Create artyom instance
var artyom = new Artyom();

// ArtyomVoicesIdentifiers is an object that stores the voices
// that could be found in the browser according to a language and region identifier
// Every item is an array : ArtyomVoicesIdentifiers["en-US"] = ["Google US English","en-US","en_US"]

// A. To prefer your voices (push to the beginning of the array)
artyom.ArtyomVoicesIdentifiers["en-US"].unshift('Google US English', 'Alex');
// And the identifiers of en-US should look now like:
// ['Google US English', 'Alex', "Google US English","en-US","en_US"]

// B. Or if you want to delete the default voices of Artyom
artyom.ArtyomVoicesIdentifiers["en-US"] = ['Google US English', 'Alex'];

// rest of your code 
artyom.initialize({
    // .. Rest of your code 
})
```
