### ISSUE TITLE
Male vs Female

### ISSUE THREAD

**Issue by bannostookaylo** [sdkcarlos/artyom.js#39]
When I get a list of my voices I see "English UK Male" and "English UK Female" ... how do I get Artyom to use the English UK Female voice?

**Comment by sdkcarlos** [comment]
Just change the order of voice, artyom takes the first voice available for a language, so the order to select the female first when available would be:

```javascript
const myAssistant = new Artyom();

// Change voice order:
// original object property prefers male voice: 
// "en-GB": ["Google UK English Male", "Google UK English Female", "en-GB", "en_GB"],

// Prefer Female voice
myAssistant.ArtyomVoicesIdentifiers["en-GB"] = ["Google UK English Female", "Google UK English Male", "en-GB", "en_GB"];

// Rest of your code
```

**Comment by mgkaradag** [comment]
How can I pick a female voice on iOS? This solution does not work on iOS.
