### ISSUE TITLE
Google discontinuing Electron support?

### ISSUE THREAD

**Issue by ericxtang** [sdkcarlos/artyom.js#4]
Saw this thread in StackOverflow. http://stackoverflow.com/questions/36214413/webkitspeechrecognition-returning-network-error-in-electron

I'm using Artyom with Electron - can anyone confirm it's no longer supported?

**Comment by sdkcarlos** [comment]
Indeed @ericxtang i've just tested with older and the latest version of Electron Framework, and it seems to be true.

The initialization of a webkitSpeechRecognition object will trigger the error with code `"network"`

```javascript
artyom.when("ERROR",function(e){
    console.error(e);
});

artyom.initialize({
   lang:"en-GB",
   debug:true,
   listen:true,
   continuous:true
});
```

![artyom_errr](https://cloud.githubusercontent.com/assets/11634719/16070324/d4941ed4-32d4-11e6-8edd-81095285fcfb.png)

> It seems like google had revoked the speech api access in development or embedded chromium environments.
> [Atom Discussion](https://discuss.atom.io/t/webkitspeechrecognition-google-webkit-speech-api-throws-network-error-in-electron-app/27958)

The feature was working a couple of weeks ago, i wrote an article about it [here](http://ourcodeworld.com/articles/read/165/voice-commands-speech-recognition-and-speech-synthesis-with-electron-framework), but now comes this ... that makes me sad :cry:

I'll keep the issue open, hopefully is a bug ... or maybe is the end of the speechRecognition for Electron, thanks for pointing out this issue !

**Comment by ericxtang** [comment]
Thanks for verifying @sdkcarlos!  Hopefully the new google could API will continue to be free.  

In the mean time, does anyone have recommendations for an alternative?  I tried out the @watson-developer-cloud api but it can get quite expensive as you get through the first 1000 hour.

**Comment by gedw99** [comment]
use the OS level speech recognition. For example on OSX its there.
https://support.apple.com/en-us/HT202584

I have seen it used with Electron before.

**Comment by sdkcarlos** [comment]
The service that Google built into Chromium doesn't appear to be working in shell environments like Electron anymore.

**Comment by beevelop** [comment]
@sdkcarlos Since this happened over a year ago, are there any suitable alternatives for getting speech recognition working with Electron?

**Comment by si458** [comment]
@beevelop the only alternatives i have found are Amazon Transcribe, IBM Watson speech to text or Google Speech API, but they are all paid services, and very expensive in the long run 👎

**Comment by SannanOfficial** [comment]
Any suggestions on this in 2023?
