### ISSUE TITLE
Can't distinguish between words that sound the same

### ISSUE THREAD

**Issue by petahcole** [sdkcarlos/artyom.js#40]
I'm trying to use artyom.addCommands to listen to voice and trigger different keystrokes on a digital keyboard. Artyom has trouble distinguishing between "four" and "for", "C" and "see", etc. I've tried several ways to work around this, am I just missing a way to train it?

**Comment by athuldevin** [comment]
Artyom is using chrome built in speech recognition which uses google stt
service .It is not a problem of artyom. try uxing sentences which will give
you a better result
