### ISSUE TITLE
Loop in React

### ISSUE THREAD

**Issue by hmontes** [sdkcarlos/artyom.js#41]
If i use your excellent package in React, i get a loop when i spoke a phrase. How can i fix that?

```
componentDidMount() {
    const assistent = new Artyom();
    assistent.addCommands([
      {
        indexes: ['Buenos días'],
        action: (i) => {
          assistent.say("Buenos días. ¿Como amaneciste?")
        }
      },
      {
        indexes: ['Buenas tardes'],
        action: (i) => {
          assistent.say("Buenas tardes. ¿Como ha estado tu día?")
        }
      }
    ])
  
    assistent.initialize({
      lang: "es-ES",
      continuous: true, // Listen forever
      soundex: true,// Use the soundex algorithm to increase accuracy
      debug: true, // Show messages in the console
      // executionKeyword: "and do it now",
      listen: true, // Start to listen commands !
  
      // If providen, you can only trigger a command if you say its name
      // e.g to trigger Good Morning, you need to say "Jarvis Good Morning"
      // name: "Jarvis" 
    })
  }
```

If i say "Buenos días" the browser answer "Buenos días. ¿Como amaneciste?" in a loop (never ends). How can i fix that issue? I think you need to delete the request after the system spoke

Thanks

**Comment by hmontes** [comment]
I found the bug. The system listen "**Buenos días**. ¿Como amaneciste?". So, hears again "Buenos días" and enter to a loop. If i change the answer for "Hola. ¿Como amaneciste?" The loop disappear.

So. I suggest you temporarily disable the listen when the system is spoke.

**Comment by sdkcarlos** [comment]
See my comment at the issue https://github.com/sdkcarlos/artyom.js/issues/7 for a solution.
