### ISSUE TITLE
Doc link + Cordova or Phonegap 

### ISSUE THREAD

**Issue by kiralikbeyin** [sdkcarlos/artyom.js#45]
Doc link in wiki doesnt work.

Can i use this lib in a cordova/phonegap app?

**Comment by sdkcarlos** [comment]
Hi, the docs of the lib can be found [in this website](https://docs.ourcodeworld.com/projects/artyom-js). Pitifully, the Speech APIs aren't available on the WebView of Android nor other mobile devices (only Google Chrome Browser).

**Comment by maitmansour** [comment]
Hello,
You can use it with Cordova by installing this plugin : cordova-plugin-speechrecognition
This provide the native speech recognition, then you can add comands and use them with the native Speech  : 

```js
function startRecognition() {
    window.plugins.speechRecognition.startListening(function(result) {
//Speech Recog Result
        result.forEach(function(option) {
//Artyom will check if there is commands with same words and execute them
            if (artyom.simulateInstruction(option)) {
                console.log("Matched : " + option, result);
                return;
            }
        });

        console.log(result);
    }, function(err) {
        console.error(err);
    }, {
        language: "en-US",
        showPopup: false
    });
}
```

PS : Artyom.say didn't work actually, but if i found how to make it work, i will share it here !
