### ISSUE TITLE
Artiom can't recognize voice without the Speech Recognition API.

### ISSUE THREAD

**Issue by tocka9** [sdkcarlos/artyom.js#54]
I'm getting an error in my console when opening the page with Firefox "Artiom can't recognize voice without the Speech Recognition API.". Everything works fine on Chrome. How could I fix this? Or disable the error?

**Comment by sdkcarlos** [comment]
Artyom only works in Google Chrome. You need to verify if the browser supports the API before initializing an instance of Artyom:

```javascript
// If speech recognition supported
if (window.hasOwnProperty('webkitSpeechRecognition')) {
    let artyom = new Artyom();

    // your code that requires artyom.
}
```
So you won't get the message in the console. The same happens with the Speech Synthesis API, so you may want to check for both APIs:


```javascript
// If Artyom can use both features
if (window.hasOwnProperty('webkitSpeechRecognition') && window.hasOwnProperty('speechSynthesis')) {
    let artyom = new Artyom();

    // your code that requires artyom.
}
```
